services:
  - type: web
    name: eshop-django
    runtime: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn config.wsgi --log-file -"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DB_ENGINE
        value: sqlite
