# Generated by Django 6.1.1 on 2026-09-19 10:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=16, validators=[accounts.models.validate_egyptian_phone]),
        ),
    ]
