# Generated by Django 6.1.1 on 2026-09-19 10:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=11, validators=[accounts.models.validate_egyptian_phone]),
        ),
    ]
